NEW Create action
silverstripe/gha-update-js pull request #1
Opened 2022-05-30 23:50 UTC by emteknetnz

Note: hasn't been tested yet, hold of merging this

2022-06-03 03:09 UTC, GuySartorelli requested changes

2022-06-03 03:09 UTC, GuySartorelli commented on action.yml
> +        JSON=$(curl https://api.github.com/repos/${{ github.repository }}/branches)
Why are we using the api to check for branches, but then below we're using git directly to delete the branch?
It seems like it would make more sense to do `git branch -r --list pulls/*/update-js-*` or similar - or if that pattern isn't strict enough, `git branch -r --list` piped into grep or looped over and checked with a regex test or something.

2022-06-03 03:09 UTC, GuySartorelli commented on action.yml
> +        CUT=$(echo ${{ github.ref }} | cut -c 12-)
If `CUT` represents the name of the target branch, lets call it `TARGET_BRANCH` or something similarly descriptive.

2022-06-07 04:17 UTC, emteknetnz commented on README.md
> +
Added

2022-06-07 04:23 UTC, emteknetnz commented on action.yml
> +      uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
I don't think we need to specify the exact `@v2.4.2` version here - I think simply saying `@v2` suffices.  We are creating a quasi lockfile here, if we needed to get a more recent verson, then the idea is we visit the v2 tag on github and copy the new sha from that.  Standard practice in github actions land is to use `@v2` references, we're going one step beyond that for security reasons though I'd like us to be able to refer to the `@v2` tags rather than the patch tags

In the rare instance if we ever really need to find out the exact patch release it refered to, say we need to see if we have a security patch, then we'll be willing to spend 10 minutes to manually go through the git history

2022-06-07 04:26 UTC, emteknetnz commented on action.yml
> +      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e #v1
Copy paste from the example I used probably :-)

I'll update it to `v3`

2022-06-07 04:29 UTC, emteknetnz commented on action.yml
> +        cd ..
Yes, this action is explicitly for a small number of our own modules.  It's not really intended for general consumption

2022-06-07 04:30 UTC, emteknetnz commented on action.yml
> +        git checkout 1
Yes, workflow will be setup to only run on the default branch, which is currently `4` or `1`

2022-06-07 04:35 UTC, emteknetnz commented on action.yml
> +        NODE_ENV=production node_modules/webpack/bin/webpack.js -p --bail --progress
Can't remember exact reason why not using just `webpack` possibly symlink issue? No harm in using the full relative path so keep as is IMO

> Is it feasible to instead split it up by reading the scripts.build key in package.json

They don't differ as far as I know, I think it's much cleaner to be explicit in the action what we're doing, rather than try to do things dynamically.  For instance we cannot dynamically create new steps if there are different things in the `scripts.build`

> yarn build doesn't run this part if linting or testing fail. Is that also the case for this action?

No, there's a comment above explaining that I want the PR created, knowing that it will fail, so the team has visibility of a failure so it can be corrected

2022-06-07 04:36 UTC, emteknetnz commented on action.yml
> +      if: always()
Yes remove old PR.  New PR with failed action will be created, giving us visibility of the failure

Once fixed, we can manually re-run the action via `workflow_dispatch` e.g. https://github.com/silverstripe/silverstripe-asset-admin/blob/1/.github/workflows/update-js-deps.yml#L6

2022-06-07 05:02 UTC, emteknetnz commented on action.yml
> +        JSON=$(curl https://api.github.com/repos/${{ github.repository }}/pulls)
UPdated

2022-06-07 05:03 UTC, emteknetnz commented on action.yml
> +        for NUMBER in $NUMBERS; do
There were multiple PRs because the previous close all the PRs action failed :-)

Possibly someone manually reopening and old one is another scenario

2022-06-07 05:05 UTC, emteknetnz commented on action.yml
> +        JSON=$(curl https://api.github.com/repos/${{ github.repository }}/branches)
Not sure if actions/checkout will give us all the branch names by default.  The API is fast and we're using that elsewhere to check if things exist, and it gives us json which is much nicer to parse than git cli output

2022-06-07 05:11 UTC, emteknetnz commented on action.yml
> +    - name: Generate branch name
No, and default github.token won't allow creating pull-requests in anything except the account/repo that's running the workflow

2022-06-07 05:12 UTC, emteknetnz commented on action.yml
> +        CUT=$(echo ${{ github.ref }} | cut -c 12-)
I dunno, it's just a tmp variable, we use it the line below

Honestly think calling it anything with the word 'BRANCH' in it will just make it more confusing since we create $BRANCH directly below

2022-06-07 05:13 UTC, emteknetnz commented on action.yml
> +      if: always()
Yes.  The PR will include a red cross which we can click on to easily see why this failed

2022-06-09 05:36 UTC, GuySartorelli commented on action.yml
> +    - name: Generate branch name
Unfortunate but nothing we can do. Okie doke.

2022-06-09 05:40 UTC, GuySartorelli commented on action.yml
> +        CUT=$(echo ${{ github.ref }} | cut -c 12-)
Suboptimal but in this specific situation it's clear enough that it doesn't matter too much. Happy to leave as is.

2022-06-09 05:42 UTC, GuySartorelli approved these changes
Looks good

2022-06-09 05:42 UTC, merged